# App Engine Flexible environment configuration
runtime: python
env: flex
service: default

runtime_config:
  operating_system: ubuntu22
  python_version: 3.9

env_variables:
  ENV: production

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

manual_scaling:
  instances: 1

handlers:
- url: /static/(.*)
  static_files: static/\1
  upload: static/.*
  secure: optional

- url: /.*
  script: auto
  secure: optional