# Python App Engine Flexible Environment configuration
runtime: python39
env: standard  # This line enables the flexible environment
entrypoint: gunicorn -b :$PORT main:app  # How the application will be started

manual_scaling:
  instances: 1  # Required for Flexible, no auto-scaling allowed

# Instance class controls the resources available to your app
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Environment variables
env_variables:
  ENV: 'production'
  # Add other environment variables here

# Static file handlers if needed
handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto


  # All other URLs are handled by your application
  - url: /.*
    script: auto