runtime: python
env: flex
entrypoint: gunicorn -b :$PORT application:application

runtime_config:
  operating_system: "ubuntu22"
  python_version: "3.9"

# Resource settings
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Scaling settings
manual_scaling:
  instances: 1

readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1800