# Python App Engine Flexible Environment configuration
runtime: python
env: flex  # This line enables the flexible environment
entrypoint: gunicorn -b :$PORT main:app  # How the application will be started

beta_settings:
  # Required for Python Flex post-2023
  use_deprecated_vm_runtime: true  # Acknowledge deprecation


# Runtime configuration
runtime_config:
  operating_system: ubuntu22  # Latest supported Ubuntu OS
  python_version: 3.10  # Specify Python version (optional if using latest)

# Instance class controls the resources available to your app
resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10

# Scaling configuration
manual_scaling:
  instances: 1  # Start with a single instance

# Environment variables
env_variables:
  ENV: 'production'
  # Add other environment variables here

# Static file handlers if needed
handlers:
  # Serve static files from the 'static' directory
  - url: /static
    static_dir: static

  # All other URLs are handled by your application
  - url: /.*
    script: auto